### ISSUE TITLE
How to create super_resolution_esrgan NEW model?

### ISSUE THREAD

**Issue by huseyinseyit** [tensorflow/flutter-tflite#161]
Default model works only input 50*50 output 200*200px
I want the output image to be 1024*1024px or any size the user wants. What kind of model should I use for this or how can I make this model? So I want to create a new model like this file;  esrgan-tf2.tflite

**Comment by PaulTR** [comment]
So unfortunately this is outside of the scope of this repo and my own experience/knowledge (this is focused on inference and implementation rather than training), but I did a quick search online and found [some tutorials](https://medium.com/missinglink-deep-learning-platform/zero-shot-super-resolution-part-3-training-the-model-a3bf5cdcf52c) that go over this. Seems like a bit more of an intermediate/advanced topic in the training space FWIW.
