### ISSUE TITLE
Update Flutter package/plugin dependencies

### ISSUE THREAD

**Issue by PaulTR** [tensorflow/flutter-tflite#20]
Currently using older versions of dependencies. Sounds like this causes issues for devs who want to use the tflite plugin with their apps while using newer versions of things like ffi.

**Comment by DevNim98** [comment]
Hello @PaulTR, I'm currently using the tflite plugin and had to upgrade ffi in pubspec manually in order to upgrade other packages, just like someone did it here https://github.com/am15h/tflite_flutter_plugin/issues/212, after that I had no problems with other dependencies.

However I think tflite_flutter is greatly used along with tflite_flutter_helper, and the second is the one making problems with dependencies, especially with the image package since a new major version recently came out. So I was wondering, is tflite_flutter_helper also getting upgrades and support from the Tensorflow team, or just tflite_flutter. Don't know if it would be better to include what tflite_flutter_helper does inside tflite_flutter and just have one package, maintain both, or just get rid of the helper and find another way to do what the package does which is mainly image processing.

Hope more contributors come to help since this is quite an important package to flutter, especially now with the AI boom, I guess many people just forgot about this package since it didn't receive support for more than 2 years and rather preferred to use native code instead of depending of an old package. Have you thought of making some type of announcement about getting more contributors somewhere else? Like in a video on the Flutter Youtube channel? Or maybe in a post on the coming Google I/O?

**Comment by PaulTR** [comment]
Hey @DevNim98!

> is tflite_flutter_helper also getting upgrades and support from the Tensorflow team, or just tflite_flutter

Just tflite-flutter :) Rather than using the helper around it, we're building a new plugin from the ground up, with best practices, for MediaPipe (https://developers.google.com/mediapipe)

We're currently in a transitioning period as that gets put together, but the goal is within a few months. This'll separate the super-user plugin (flutter-tflite) from the common tasks plugin (mediapipe).

> Have you thought of making some type of announcement about getting more contributors somewhere else? Like in a video on the Flutter Youtube channel? Or maybe in a post on the coming Google I/O?

I hadn't really yet! I actually have a meeting with someone from Flutter DevRel tomorrow, so I'll bring it up. Thanks for the suggestion!

**Comment by lukehutch** [comment]
@PaulTR What happened with [flutter-mediapipe](https://github.com/google/flutter-mediapipe)? The last update was 9 months ago.

**Comment by PaulTR** [comment]
There's still PRs going in for it and actively being reviewed (most recent
was late last week).

**Comment by lukehutch** [comment]
@PaulTR thanks for the update. Is there any roadmap, or aún update on the estimated release date (was August)? I need to plan which libraries I am going to use for an upcoming release. Thanks!

**Comment by PaulTR** [comment]
Nope. Unfortunately teams and things shifted, so it's going slower than
originally planned. Honestly I've learned that giving a glimpse into "this
is what we're doing" is a huge mistake for next time :p if you're working
on something for a release, I'd use what's existing now abstracter down to
'setup' and 'infer' functions, and then convert over later.

**Comment by lukehutch** [comment]
@PaulTR fair enough. Can you please at least give any guesses as to the long term outlook of Google ML Kit vs. MediaPipe, for facial recognition specifically?
