### ISSUE TITLE
null check operator used on a null value

### ISSUE THREAD

**Issue by NQHuy1905** [tensorflow/flutter-tflite#203]
Hi, i am trying to deploy app with tflite_flutter.

But when i test the code like below, it, log out error null check operator used on a null value though as i see input and output of model is not null

Can anyone explain why

![Screenshot from 2024-03-21 11-38-10](https://github.com/tensorflow/flutter-tflite/assets/87300546/631df1e5-d67a-4cae-a7a6-45504f457dbe)

**Comment by Talha2023azzurri** [comment]
provide all code its not coming from the code you provide

**Comment by Tylerchristensen100** [comment]
I am having the same issue.  The issue is coming from `runForMultipleInputs()` in interpreter.dart

Model: blaze_face_short_range.tflite


The interpreter `outputShape` is [1,896,16] but the `outputTensors` in `runForMultipleInputs()` is [ 2, 896, 16]

```
final output = [
            List.filled(isolateModel.outputShape[1],
            List.filled(isolateModel.outputShape[2], 0.0))
];
interpreter.run(input, output);
```




interpreter.dart:
 ```
 void runForMultipleInputs(List<Object> inputs, Map<int, Object> outputs) {
    if (outputs.isEmpty) {
      throw ArgumentError('Input error: Outputs should not be null or empty.');
    }
    runInference(inputs);
    var outputTensors = getOutputTensors();
    for (var i = 0; i < outputTensors.length; i++) {
      outputTensors[i].copyTo(outputs[i]!);
    }
  }
```

**Comment by haristrilokn** [comment]
I am also getting the same error.

**Comment by harispathan03** [comment]
I am also getting the same error.
I think the reason behind this error is package implementation how the package is handling `run` method of interpreter.


```
/// Run for single input and output
  void run(Object input, Object output) {
    var map = <int, Object>{};
    map[0] = output;
    runForMultipleInputs([input], map);
  }
```

```
  /// Run for multiple inputs and outputs
  void runForMultipleInputs(List<Object> inputs, Map<int, Object> outputs) {
    if (outputs.isEmpty) {
      throw ArgumentError('Input error: Outputs should not be null or empty.');
    }
    runInference(inputs);
    var outputTensors = getOutputTensors();
    for (var i = 0; i < outputTensors.length; i++) {
      outputTensors[i].copyTo(outputs[i]!);
    }
  }
```


- In run method, map is initialized with only first index data from the output list, then this map is passed on the `runForMultipleInputs` method.
- In that method, there is a for loop which runs upto length of **outputTensors** which may be 3 or 4. It also access `outputs[i]!` which length is only 1 irrespective how long list we are passing as output in `void run(Object input, Object output)`. That's why we are getting null check operator used on a null value.

**Comment by yasseralsamman** [comment]
getting the same issue here with DeepSpeech 0.9.3 tflite model.

**Comment by lanle** [comment]
I have the same issue. How do I fix or workaround?
I am a newbie with flutter. Thank you.

**Comment by tnamIT299** [comment]
I also have the same error, has anyone here found a solution?
