### ISSUE TITLE
Building for iOS Simulator, but linking in object file built for iOS

### ISSUE THREAD

**Issue by fayis672** [tensorflow/flutter-tflite#21]
`Error (Xcode): Building for iOS Simulator, but linking in object file built for iOS, file '/Users/jithinrobert/.pub-cache/hosted/pub.dev/tflite_flutter-0.9.0/ios/TensorFlowLiteC.framework/TensorFlowLiteC' for architecture arm64`

Getting this error in ios, I added  TensorFlowLiteC_framework to pub cache

**Comment by PaulTR** [comment]
Does this work for an iOS device? I have a feeling the simulator isn't supported (could be for a variety of reasons that I haven't verified - hardware acceleration, dependency on camera, etc.)

**Comment by xyzacademic** [comment]
It works on a physical device like iPhone 13 pro Max. But I can no longer do debugging in the simulator for UI after importing this package. Each time I have to do debugging on a physical device.

**Comment by mirland** [comment]
You can try adding this in the Podfile 

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Fixes TFLite simulator issue
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 arm64'
    end
  end
end
```

I didn't test using this package, but it was working in the previous package

**Comment by fayis672** [comment]
> You can try adding this in the Podfile
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>     target.build_configurations.each do |config|
>       # Fixes TFLite simulator issue
>       config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 arm64'
>     end
>   end
> end
> ```
> 
> I didn't test using this package, but it was working in the previous package

After following these steps, I encountered another error. 
`Could not find module 'PhoneNumberKit' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, at: /Users/jithinrobert/Documents/fayis-workspace/ProductAnalyticsMobileApp/build/ios/Debug-iphonesimulator/PhoneNumberKit/PhoneNumberKit.framework/Modules/PhoneNumberKit.swiftmodule`

**Comment by fayis672** [comment]
> Does this work for an iOS device? I have a feeling the simulator isn't supported (could be for a variety of reasons that I haven't verified - hardware acceleration, dependency on camera, etc.)

This issue is only in the simulator, In real device, it's working fine. I couldn't find any documentation saying  simulator is not supported.

**Comment by DevNim98** [comment]
Hello @fayis672 ,
 
> This issue is only in the simulator, In real device, it's working fine. I couldn't find any documentation saying simulator is not supported.

the package use tflite binaries that are compiled for a specific instruction set (x86, arm64, etc), for example, if you run the emulator on a Windows machine, that machine is probably using a CPU with an x86 architecture, meaning that if you are running your application using tflite binaries that were compiled for arm64, then it won't work since those two architectures are different. You could try changing the platform of the binaries, or probably what makes more sense is if you are planning to run your application on mobile devices, then test it on real ones (physically). That way you will also be able to measure the speed and compatibility of different delegates on different devices.

**Comment by PaulTR** [comment]
| This issue is only in the simulator, In real device, it's working fine. I couldn't find any documentation saying simulator is not supported.

So I'm honestly not surprised that the simulator doesn't work - they tend to be kind of funny with the way TFLite is built. I'll make sure I add a note in a README somewhere to cover this case, plus it feels like something that will end up in the wiki when that gets made.

Thanks!
